### ISSUE TITLE
SyntaxError: Identifier 'core' has already been declared

### ISSUE THREAD

**Issue by ciaransweet** [JoseThen/comment-pr#6]
Hey there @JoseThen 😄 

I found your Action and really like the look of it, I've just tried to give it a go:

```yaml
- name: Comment on PR
        if: ${{ steps.modified.outputs.MODIFIED }} == "FALSE"
        uses: JoseThen/comment-pr@v1
        with:
          comment: |
            We've noticed your Pull Request did not modify any tests :mag:
            If your change requires tests, please add them :smile:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Unfortunately I get the following error message:

```
/home/runner/work/_actions/JoseThen/comment-pr/v1/index.js:2
const core = require('@actions/github');
      ^

SyntaxError: Identifier 'core' has already been declared
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

Do you know why this might be?
